services:
  lxp-backend:
    build:
      context: ./flask-backend
      dockerfile: Dockerfile
    container_name: lxp-backend
    environment:
      DATABASE_URL: mysql+pymysql://root:root123@shared-mysql:3306/veriton_db
      SECRET_KEY: Veriton_f8A9C4D27E1B6F5A90D3C2E8B7A6419D5E0F4C8B2A7D9E1364CFA90B8D71E52
      JWT_SECRET_KEY: Veriton_f8A9C4D27E1B6F5A90D3C2E8B7A6419D5E0F4C8B2A7D9E1364CFA90B8D71E52

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}

      LINKEDIN_CLIENT_ID: ${LINKED_CLIENT_ID}
      LINKEDIN_CLIENT_SECRET: ${LINKED_CLIENT_SECRET}

      FRONTEND_URL: ${FRONTEND_URL}

    ports:
      - "5001:5000"
    restart: unless-stopped
    networks:
      - lxp-network
      - common-db-net

  lxp-frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: lxp-frontend
    depends_on:
      - lxp-backend
    ports:
      - "5174:80"
    restart: unless-stopped
    networks:
      - lxp-network

networks:
  lxp-network:
    driver: bridge

  common-db-net:
    external: true
